# Generated by Django 5.0.6 on 2024-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PcType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pctype_name', models.CharField(db_index=True, max_length=100)),
                ('pctype_slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PcBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_model', models.CharField(max_length=55)),
                ('pc_cpu', models.CharField(blank=True, max_length=55)),
                ('pc_disk_size', models.CharField(blank=True, max_length=25)),
                ('pc_about', models.TextField(blank=True, verbose_name='Статья')),
                ('pc_date_add', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('pc_date_update', models.DateField(auto_now=True, verbose_name='Время изменения')),
                ('pc_pub', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('pc_photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('pc_slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('pc_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pctypes', to='xmainsite.pctype', verbose_name='Типы оборудования')),
            ],
            options={
                'ordering': ['-pc_date_add'],
                'indexes': [models.Index(fields=['-pc_date_add'], name='xmainsite_p_pc_date_8cfbda_idx')],
            },
        ),
    ]
