# Generated by Django 5.0.6 on 2024-05-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbase',
            name='pc_about',
            field=models.TextField(blank=True, verbose_name='--Статья'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_cpu',
            field=models.CharField(blank=True, max_length=55, verbose_name='--Процессор'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_date_add',
            field=models.DateField(auto_now_add=True, verbose_name='--Время создания'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_date_update',
            field=models.DateField(auto_now=True, verbose_name='--Время изменения'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_disk_size',
            field=models.CharField(blank=True, max_length=25, verbose_name='--Объем диска'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_model',
            field=models.CharField(max_length=55, verbose_name='--Модель **'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='--Фото'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_pub',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='--Статус'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='--Slug **'),
        ),
        migrations.AlterField(
            model_name='pcbase',
            name='pc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pctypes', to='xmainsite.pctype', verbose_name='--Типы оборудования **'),
        ),
    ]
