# Generated by Django 5.0.6 on 2024-05-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmainsite', '0002_alter_pcbase_pc_about_alter_pcbase_pc_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbase',
            name='pc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctypes', to='xmainsite.pctype', verbose_name='--Типы оборудования **'),
        ),
    ]
